ALTER TABLE agn_subseries
ADD COLUMN IF NOT EXISTS retencion_ag INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS retencion_ac INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS disposicion CHAR(2) NOT NULL DEFAULT 'CT',
ADD COLUMN IF NOT EXISTS estado_activa BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE agn_subseries
DROP CONSTRAINT IF EXISTS unique_serie_codigo,
ADD CONSTRAINT unique_serie_codigo UNIQUE (serie_id, codigo);
